[package]
name = "ab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a = {path = "../../base_crates/a"}
b = {path = "../../base_crates/b"}
